name: 'BuildMySource'
description: 'Compile operations according to my personal habits.'

inputs:
  language:
    description: C++ / C / Python
    required: false
    default: C++
  path:
    description: Source file path
    required: false
    default: src
  source:
    description: Source file name
    required: false
    default: source

runs:
  using: composite
  steps:
    - id: check-dependence
      run: |
        sudo apt update
        if [[ "${{ inputs.language }}" == "C++" || "${{ inputs.language }}" == "c++" || "${{ inputs.language }}" == "C" || "${{ inputs.language }}" == "c" ]];then
            sudo apt install -y gcc g++
        elif [[ "${{ inputs.language }}" == "Python" || "${{ inputs.language }}" == "python" ]];then
            sudo apt install -y python python3 pip
            sudo pip install pyinstaller
        else
            echo "Unsupported language."
      shell: bash

    - id: Compile
      run: |
        cd ${{ inputs.path }}
        if [[ "${{ inputs.language }}" == "C++" || "${{ inputs.language }}" == "c++" ]];then
            g++ -o test.o ${{ inputs.source }}.cpp
        elif [[ "${{ inputs.language }}" == "C" || "${{ inputs.language }}" == "c" ]];then
            g++ -o test.o ${{ inputs.source }}.c
        elif [[ "${{ inputs.language }}" == "Python" || "${{ inputs.language }}" == "python" ]];then
            pyinstaller -F ${{ inputs.source }}.py
        else
            echo "Unsupported language."
        fi
      shell: bash

branding:
  icon: cpu
  color: white